# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-29 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
