# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('circuit', models.CharField(max_length=250)),
                ('image_static', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('race_number', models.IntegerField()),
                ('fP1_date', models.DateTimeField()),
                ('fP2_date', models.DateTimeField()),
                ('fP3_date', models.DateTimeField()),
                ('quali_date', models.DateTimeField()),
                ('race_date', models.DateTimeField()),
                ('pole', models.CharField(blank=True, max_length=50)),
                ('p1', models.CharField(blank=True, max_length=50)),
                ('p2', models.CharField(blank=True, max_length=50)),
                ('p3', models.CharField(blank=True, max_length=50)),
                ('p4', models.CharField(blank=True, max_length=50)),
                ('p5', models.CharField(blank=True, max_length=50)),
                ('p6', models.CharField(blank=True, max_length=50)),
                ('p7', models.CharField(blank=True, max_length=50)),
                ('p8', models.CharField(blank=True, max_length=50)),
                ('p9', models.CharField(blank=True, max_length=50)),
                ('p10', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PilotInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=3)),
                ('number', models.IntegerField()),
                ('helmet_static', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
