# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao_info', '0004_auto_20160811_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpinfo',
            name='p1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='gpinfo',
            name='p10',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='gpinfo',
            name='p2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='gpinfo',
            name='p3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='gpinfo',
            name='p4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='gpinfo',
            name='p5',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='gpinfo',
            name='p6',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='gpinfo',
            name='p7',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='gpinfo',
            name='p8',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='gpinfo',
            name='p9',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='gpinfo',
            name='pole',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
