# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolao_info', '0005_auto_20160811_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpinfo',
            name='race_number',
        ),
    ]
