# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao_info', '0008_auto_20160811_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpinfo',
            name='pole',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
