# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolao_info', '0009_auto_20160811_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpinfo',
            name='pole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='gp_pole', to='bolao_info.PilotInfo'),
        ),
    ]
