# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao_info', '0012_auto_20160811_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpinfo',
            name='double_points',
            field=models.BooleanField(default=False),
        ),
    ]
