# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao_info', '0013_gpinfo_double_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpinfo',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
