# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-18 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolao_info', '0014_gpinfo_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpinfo',
            name='BestLap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gp_BestLap', to='bolao_info.PilotInfo'),
        ),
        migrations.AddField(
            model_name='gpinfo',
            name='Dod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gp_DoD', to='bolao_info.PilotInfo'),
        ),
    ]
