# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-18 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolao_info', '0015_auto_20190318_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpinfo',
            old_name='Dod',
            new_name='DoD',
        ),
    ]
