# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 03:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bolao_info', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('GPrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolao_info.GPInfo')),
                ('p1', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='p1', to='bolao_info.PilotInfo')),
                ('p10', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='p10', to='bolao_info.PilotInfo')),
                ('p2', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='p2', to='bolao_info.PilotInfo')),
                ('p3', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='p3', to='bolao_info.PilotInfo')),
                ('p4', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='p4', to='bolao_info.PilotInfo')),
                ('p5', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='p5', to='bolao_info.PilotInfo')),
                ('p6', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='p6', to='bolao_info.PilotInfo')),
                ('p7', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='p7', to='bolao_info.PilotInfo')),
                ('p8', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='p8', to='bolao_info.PilotInfo')),
                ('p9', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='p9', to='bolao_info.PilotInfo')),
                ('pole', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pole', to='bolao_info.PilotInfo')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
