# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolao_bet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbet',
            name='p1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p1', to='bolao_info.PilotInfo'),
        ),
        migrations.AlterField(
            model_name='userbet',
            name='p10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p10', to='bolao_info.PilotInfo'),
        ),
        migrations.AlterField(
            model_name='userbet',
            name='p2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p2', to='bolao_info.PilotInfo'),
        ),
        migrations.AlterField(
            model_name='userbet',
            name='p3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p3', to='bolao_info.PilotInfo'),
        ),
        migrations.AlterField(
            model_name='userbet',
            name='p4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p4', to='bolao_info.PilotInfo'),
        ),
        migrations.AlterField(
            model_name='userbet',
            name='p5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p5', to='bolao_info.PilotInfo'),
        ),
        migrations.AlterField(
            model_name='userbet',
            name='p6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p6', to='bolao_info.PilotInfo'),
        ),
        migrations.AlterField(
            model_name='userbet',
            name='p7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p7', to='bolao_info.PilotInfo'),
        ),
        migrations.AlterField(
            model_name='userbet',
            name='p8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p8', to='bolao_info.PilotInfo'),
        ),
        migrations.AlterField(
            model_name='userbet',
            name='p9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p9', to='bolao_info.PilotInfo'),
        ),
        migrations.AlterField(
            model_name='userbet',
            name='pole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pole', to='bolao_info.PilotInfo'),
        ),
    ]
