# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao_bet', '0003_usergppoints_usertotalpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbet',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
