# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolao_info', '0013_gpinfo_double_points'),
        ('bolao_bet', '0004_userbet_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertotalpoints',
            name='GPrix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bolao_info.GPInfo'),
        ),
    ]
